app/user/api/urls.py
from django.urls import path

from user.api import views

app_name = "api-user"

urlpatterns = [
    path("create/", views.CreateUserView.as_view(), name="create"),
    path("authenticate/", views.CreateTokenView.as_view(), name="authenticate"),
    path("my-account/", views.ManageUserView.as_view(), name="my-account"),
    path("current-user/", views.CurrentUserApiView.as_view(), name="current-user"),
]

app/user/urls.py
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.urls import path, reverse_lazy

from user import views

app_name = 'user'

urlpatterns = [
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('register', views.register, name='register'),
    path('profile', views.profile, name='profile'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('password-reset/', PasswordResetView.as_view(success_url=reverse_lazy('user:password_reset_done')),
         name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

app/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

from core.models import User, MyProfile


class UserLoginForm(forms.Form):
    """Login User Form"""
    email = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['email', 'name', 'password1', 'password2']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email):
            raise forms.ValidationError(u'Email addresses must be unique.')
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 != password2:
            raise ValidationError("Passwords do not match")

        return password2


class MyProfileForm(forms.ModelForm):
    """User Details"""
    class Meta:
        model = MyProfile
        fields = ['position', 'image']

app/user/api/views.py
from rest_framework import generics, authentication, permissions, views
from rest_framework.authtoken.views import ObtainAuthToken
from rest_framework.response import Response
from rest_framework.settings import api_settings
from user.api.serializers import UserSerializer, AuthTokenSerializer

from user.api.serializers import UserSerializer


class CreateUserView(generics.CreateAPIView):
    """Create a new user in the system"""
    permission_classes = (permissions.AllowAny,)
    serializer_class = UserSerializer  # generic view - specify serializer you want to use only


class CreateTokenView(ObtainAuthToken):
    """Create a new auth token for user"""
    serializer_class = AuthTokenSerializer
    renderer_classes = api_settings.DEFAULT_RENDERER_CLASSES


class ManageUserView(generics.RetrieveUpdateAPIView):
    """Manage the authenticated user"""
    serializer_class = UserSerializer
    authentication_classes = (authentication.TokenAuthentication, authentication.SessionAuthentication)
    permission_classes = (permissions.IsAuthenticated,)

    def get_object(self):
        """Retrieve and return authenticated user"""
        return self.request.user


class CurrentUserApiView(views.APIView):
    """Get currently logged user"""
    authentication_classes = (authentication.TokenAuthentication, authentication.SessionAuthentication)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request):
        serializer = UserSerializer(request.user)
        return Response(serializer.data)

app/user/views.py
from django.contrib import messages, auth
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from core import models
from .forms import UserLoginForm, UserRegistrationForm, MyProfileForm


def login(request):
    """A view that manages the login form"""
    if request.method == 'POST':
        login_form = UserLoginForm(request.POST)
        if login_form.is_valid():
            user = auth.authenticate(email=request.POST['email'],
                                     password=request.POST['password'])

            if user:
                auth.login(request, user)
                messages.success(request, "You have successfully logged in")
                return redirect('/')
            else:
                messages.error(request, "Incorrect username or password")
    else:
        login_form = UserLoginForm()

    args = {'login_form': login_form, 'next': request.GET.get('next', '')}
    return render(request, 'login.html', args)


def register(request):
    """A view that manages the registration form"""
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            user_form.save()
            user = auth.authenticate(email=request.POST.get('email'),
                                     password=request.POST.get('password1'))

            if user:
                auth.login(request, user)
                messages.success(request, "You have successfully registered")
                return redirect('/')

            else:
                messages.error(request, "Unable to log you in at this time!")
    else:
        user_form = UserRegistrationForm()

    args = {'user_form': user_form}
    return render(request, 'register.html', args)


@login_required
def logout(request):
    auth.logout(request)
    messages.success(request, 'You have successfully logged out')
    return redirect('/')


@login_required
def profile(request):
    my_profile = get_object_or_404(models.MyProfile, owner=request.user)

    context = {'user': request.user, 'my_profile': my_profile}

    return render(request, 'profile.html', context)


@login_required
def edit_profile(request):
    my_profile = get_object_or_404(models.MyProfile, owner=request.user)
    my_details_form = MyProfileForm(request.POST, request.FILES, instance=my_profile)
    if request.method == 'POST':
        if my_details_form.is_valid():
            my_profile.save()

            return redirect(reverse('user:profile'))

    return render(request, 'edit_profile.html', {'my_profile': my_profile, 'my_details_form': my_details_form})

app/user/templates/edit_profile.html
{% extends "base.html" %} {% load staticfiles %}{% load materializecss %}
{% block extrahead %}
<link href="{% static 'css/forms.css' %}" rel="stylesheet"/>
{% endblock %}
{% load bootstrap_tags %}
{% block content %}
{% block row_header %}
<div class="row row-message">
  {% if messages %}
  {% for message in messages %}
  {% if message.tags == "success" %}
  <div class="alert alert-success">
    <div class="messages text-center">
      {{ message }}
    </div>
  </div>
  {% else %}
  <div class="alert alert-danger">
    <div class="messages text-center">
      {{ message }}
    </div>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
</div>
{% endblock %}
<div class="form-container">
    <form class="form-signin" method="POST" enctype="multipart/form-data">
        <i class="material-icons" id="icon-login">person</i>
        <fieldset class="form-box">
            <div class="row text-center">
                <h4>Edit Profile</h4>
            </div>
            <div class="row text-center">
                <div class="input-field col s6">
                    <div class="input-field col s12 field-description">
                        <h6>Your Position:</h6>
                    </div>
                    <div class="input-field col s12 field-description">
                        <h6>Your Portait:</h6>
                    </div>
                </div>
                <div class="input-field col s6">
                    {% csrf_token %}
                    {{ my_details_form | materializecss }}
                </div>
            </div>
            <button type="submit" class="btn-login"><span>Continue <i class="far fa-arrow-alt-circle-right"></i></span>
            </button>
        </fieldset>
    </form>
  </div>
{% endblock %}

app/user/templates/login.html
{% extends "base.html" %} {% load staticfiles %}{% load materializecss %}
{% block extrahead %}
<link href="{% static 'css/forms.css' %}" rel="stylesheet"/>
{% endblock %}
{% load bootstrap_tags %}

{% block content %}
<div id="page-index">



  <div class="form-container">

    <form class="form-signin" method="post" action="{% url 'user:login' %}">
      <i class="material-icons" id="icon-login">lock</i>
      <fieldset class="form-box">
        <div class="row text-center">
          <h4>Login User</h4>
        </div>
        <div class="row text-center">
          <div class="input-field col s6">
            <div class="input-field col s12 field-description">
              <h6>Your Email Address:</h6>
            </div>
            <div class="input-field col s12 field-description">
              <h6>Your Password:</h6>
            </div>
          </div>
          <div class="input-field col s6">
            {% csrf_token %}
            {{ login_form |materializecss }}
          </div>
        </div>
        <div class="row text-center">

        </div>
        <button type="submit" class="btn-login"><span>Continue <i class="far fa-arrow-alt-circle-right"></i></span>
        </button>
      </fieldset>
    </form>
  </div>
  <!-- /container -->
</div>
{% endblock %}

app/user/templates/profile.html
{% extends "base.html" %} {% load staticfiles %}
{% block extrahead %}
<link href="{% static 'css/forms.css' %}" rel="stylesheet"/>
{% endblock %}
{% load bootstrap_tags %}
{% block content %}
{% block row_header %}
<div class="row row-message">
  {% if messages %}
  {% for message in messages %}
  {% if message.tags == "success" %}
  <div class="alert alert-success">
    <div class="messages text-center">
      {{ message }}
    </div>
  </div>
  {% else %}
  <div class="alert alert-danger">
    <div class="messages text-center">
      {{ message }}
    </div>
  </div>
  {% endif %}
  {% endfor %}
  {% endif %}
</div>

{% endblock %}
<div class="form-container">

  <div class="user-profile">
    <div class="row plain-element">
      <div class="col s3 m3 l3 plain-element col-background">

      </div>
      <div class="col s9 m9 l9 text-center col-profile">
        <div class="row plain-element">
          <br>
          <div class="portrait">
            {% if my_profile.image %}
            <img src="{{ my_profile.image.url }}" class="img responsive img-portrait">
            {% else %}
            <img src="{% static 'img/portraits/default.jpg' %}" class="img-responsive img-portrait">
            {% endif %}
          </div>
        </div>
        <div class="row plain-element">
           <h5>{{ user.name }}<span class="flex"> <button class="btn-edit" onclick="window.location='{% url 'user:edit_profile' %}'">Edit</button></span>

        </div>
        <div class="row plain-element">
          <h6> Email: <b>{{ my_profile.owner }}</b></h6>
        </div>
        <div class="row plain-element">
          <h6> Position: <b>{{ my_profile.position }}</b></h6>
        </div>

      </div>
    </div>
  </div>
</div>
<!-- /container -->


{% endblock %}

app/user/templates/register.html
{% extends "base.html" %} {% load staticfiles %}{% load materializecss %}
{% block extrahead %}
<link href="{% static 'css/forms.css' %}" rel="stylesheet"/>
{% endblock %}
{% load bootstrap_tags %}

{% block content %}


<div class="form-container">

    <form class="form-signin" method="post" action="{% url 'user:register' %}" class="accountform">
        <i class="material-icons" id="icon-login">assignment_turned_in</i>
        <fieldset class="form-box">
            <div class="row text-center">
                <h4>Register User</h4>
            </div>
            <div class="row text-center">
                <p>Already got an account? <a href="{% url 'user:login' %}">Log In</a></p>
            </div>
            <div class="row text-center">
                <div class="input-field col s6">
                    <div class="input-field col s12 field-description">
                        <h6>Your Email Address:</h6>
                    </div>
                    <div class="input-field col s12 field-description">
                        <h6>Your Username:</h6>
                    </div>
                    <div class="input-field col s12 field-description">
                        <h6>Your Password:</h6>
                    </div>
                    <div class="input-field col s12 field-description">
                        <h6>Confirm Password:</h6>
                    </div>
                </div>
                <div class="input-field col s6">
                    {% csrf_token %}
                    {{ user_form|materializecss }}
                </div>
            </div>
            <button type="submit" class="btn-login"><span>Continue <i class="far fa-arrow-alt-circle-right"></i></span>
            </button>
        </fieldset>
    </form>
</div>
<!-- /container -->

{% endblock %}